### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by roncham** [davideast/hnpwa-api#9]
Not sure where I went wrong
```
TypeError: Cannot read property 'apply' of undefined
    at /user_code/node_modules/hnpwa-api/node_modules/express/lib/router/index.js:635:14
    at next (/user_code/node_modules/hnpwa-api/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/user_code/node_modules/hnpwa-api/node_modules/express/lib/router/index.js:174:3)
    at router (/user_code/node_modules/hnpwa-api/node_modules/express/lib/router/index.js:47:12)
    at corsServer (/user_code/node_modules/hnpwa-api/index.js:28:17)
    at cors (/user_code/node_modules/hnpwa-api/node_modules/cors/lib/index.js:188:7)
    at /user_code/node_modules/hnpwa-api/node_modules/cors/lib/index.js:224:17
    at originCallback (/user_code/node_modules/hnpwa-api/node_modules/cors/lib/index.js:214:15)
    at /user_code/node_modules/hnpwa-api/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/user_code/node_modules/hnpwa-api/node_modules/cors/lib/index.js:199:9)
```

Also a question. I'm trying to use this with AMP, but I need to add Items: to the json output. Where can I edit to include this?
```
{ 
Items: 
[{ original HN json here }] 
}
```

**Comment by kevmoo** [comment]
I think this package is outdated WRT the latest `firebase-functions` code. v0.5 vs 1.0.2

@davideast – thoughts?
